PyeongSaeng/PyeongSaeng-BE

.github/ISSUE_TEMPLATE/docs.yml, .github/ISSUE_TEMPLATE/setting.yml, .github/workflows/ci-cd.yml, Dockerfile, build.gradle, src/main/java/com/umc/pyeongsaeng/global/common/HealthController.java, src/main/resources/application-local.yml, src/main/resources/application-prod.yml, src/main/resources/application.yml
#1
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
N/A
swagger 2.4.0에서 오류나서 2.8.0으로 올렸습니다.
=> ⚙️ [Setting] CI/CD설정

src/main/java/com/umc/pyeongsaeng/global/common/HealthController.java, src/main/java/com/umc/pyeongsaeng/global/config/SecurityConfig.java
#15 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용
N/A
=> 🐛 [Fix] CICD Health 안되는 버그 수정

src/main/java/com/umc/pyeongsaeng/domain/auth/controller/AuthController.java, src/main/java/com/umc/pyeongsaeng/domain/sms/controller/SmsController.java, src/main/java/com/umc/pyeongsaeng/domain/token/controller/TokenController.java, src/main/java/com/umc/pyeongsaeng/global/common/HealthController.java, src/main/java/com/umc/pyeongsaeng/global/config/SwaggerConfig.java
closed #19 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용
N/A
인증이 필요하지 않은 API에 대해 보안 설정 제외 처리를 진행했습니다. 
- 현재 보안 설정은 S3 API와 로그아웃 API에만 적용되어 있으며 나머지 API는 인증 없이 접근 가능합니다.
- 인증이 필요 없는 API에 대해 security = {} 설정을 통해 Swagger 문서에서 보안 미적용 상태로 표시하려 했으나 적용되지 않는 문제가 있었습니다.
- 해당 문제는 이슈( https://github.com/swagger-api/swagger-core/issues/2844) 를 참고하여 @SecurityRequirement 어노테이션으로 처리하였고 Swagger 버전 문제로 추정하고 있습니다.
추가로 보안 적용이 필요한 API가 있는지 확인 부탁드립니다.
=> 🚀[Chore] Swagger 보안 설정 업데이트

src/main/java/com/umc/pyeongsaeng/domain/company/repository/CompanyRepository.java, src/main/java/com/umc/pyeongsaeng/domain/job/controller/JobPostController.java, src/main/java/com/umc/pyeongsaeng/domain/job/converter/JobPostConverter.java, src/main/java/com/umc/pyeongsaeng/domain/job/converter/JobPostImageConverter.java, src/main/java/com/umc/pyeongsaeng/domain/job/dto/request/CompanyFormFieldRequestDTO.java, src/main/java/com/umc/pyeongsaeng/domain/job/dto/request/JobPostImageRequestDTO.java, src/main/java/com/umc/pyeongsaeng/domain/job/dto/request/JobPostRequestDTO.java, src/main/java/com/umc/pyeongsaeng/domain/job/dto/response/JobPostImageResponseDTO.java, src/main/java/com/umc/pyeongsaeng/domain/job/dto/response/JobPostResponseDTO.java, src/main/java/com/umc/pyeongsaeng/domain/job/entity/JobPost.java, src/main/java/com/umc/pyeongsaeng/domain/job/entity/JobPostField.java, src/main/java/com/umc/pyeongsaeng/domain/job/entity/JobPostImage.java, src/main/java/com/umc/pyeongsaeng/domain/job/repository/FormFieldRepository.java, src/main/java/com/umc/pyeongsaeng/domain/job/repository/JobPostFieldRepository.java, src/main/java/com/umc/pyeongsaeng/domain/job/repository/JobPostImageRepository.java, src/main/java/com/umc/pyeongsaeng/domain/job/repository/JobPostRepository.java, src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostCommandService.java, src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostCommandServiceImpl.java, src/main/java/com/umc/pyeongsaeng/global/config/SecurityConfig.java
#13 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- JobPostController, Service, Repository 추가
- JobPostController에서 쓰는 DTO를 위해 Converter 추가
- JobPost 결과를 return 할 때 순환 참조되는 문제가 있어 JobPostIamge Converter로 JobPostImageDTO 생성
- Security Config에서 /autuator/**로 수정
userDetail이 추가되면 수정해야 합니다. CompanyID를 빼고 Company를 저장할 수 있도록
=> ✨ [Feat] 기업 신청서 폼 만들기

.github/workflows/ci-cd.yml, build.gradle, src/main/java/com/umc/pyeongsaeng/domain/sms/service/SmsServiceImpl.java, src/main/java/com/umc/pyeongsaeng/global/apiPayload/code/status/ErrorStatus.java, src/main/resources/application.yml
#12
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
N/A
하루에 보낼 수 있는 sms 양을 한 사람 당 10개로 제한하였습니다.
PM님과 상의하여 링크 보내기 기능은 제거하기로 하였습니다.
=> ✨ [Feat] SMS 전송 기능

src/main/java/com/umc/pyeongsaeng/domain/job/controller/JobPostController.java, src/main/java/com/umc/pyeongsaeng/domain/job/converter/JobPostConverter.java, src/main/java/com/umc/pyeongsaeng/domain/job/dto/response/JobPostResponseDTO.java, src/main/java/com/umc/pyeongsaeng/domain/job/repository/JobPostRepository.java, src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostQueryService.java, src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostQueryServiceImpl.java, src/main/java/com/umc/pyeongsaeng/global/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc/pyeongsaeng/global/config/SecurityConfig.java, src/main/java/com/umc/pyeongsaeng/global/config/WebConfig.java, src/main/java/com/umc/pyeongsaeng/global/resolvation/annotation/PageNumber.java, src/main/java/com/umc/pyeongsaeng/global/resolvation/resolver/PageNumberArgumentResolver.java
#30 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- Page 리졸버 추가
- 기업이 쓴 게시글 조회
- CORS 프론트엔드 주소 추가
=> ✨ [Feat] 기업이 쓴 게시글 조회, Page 리졸버 추가, CORS 프론트엔드 주소 추가

src/main/resources/application.yml
#46
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
N/A
=> ✨ [Feat] Add Redis host

.github/workflows/ci-cd.yml
closed #<issue_number> : 일반 개발 이슈 <br />
fixed #<issue_number> : 버그 픽스나 핫 픽스 이슈 <br />
resolved #<issue_number> : 문의나 요청사항에 대한 이슈 <br />
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용
=> ✨ [Feat] :docker network 만드는 거 추가

src/main/java/com/umc/pyeongsaeng/domain/auth/service/AuthCommandServiceImpl.java, src/main/java/com/umc/pyeongsaeng/domain/job/controller/JobPostController.java, src/main/java/com/umc/pyeongsaeng/domain/job/converter/JobPostConverter.java, src/main/java/com/umc/pyeongsaeng/domain/job/converter/JobPostImageConverter.java, src/main/java/com/umc/pyeongsaeng/domain/job/dto/response/JobPostImageResponseDTO.java, src/main/java/com/umc/pyeongsaeng/domain/job/dto/response/JobPostResponseDTO.java, src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/service/TravelTimeService.java, src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/util/TravelTimeUtil.java, src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostQueryService.java, src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostQueryServiceImpl.java, src/main/java/com/umc/pyeongsaeng/global/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc/pyeongsaeng/global/s3/dto/S3DTO.java, src/main/resources/application-prod.yml
closed #38 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
N/A
회원가입 시 유저의 주소지 좌표를 API를 이용해 저장하는 로직을 추가했습니다.
이미지는 presignedUrl을 바로 프론트로 넘겨주도록 구성해봤는데, 어떠신가요?
keyName만 넘겨주고 프론트에서 presignedUrl을 요청해 가져오는 방식도 있을 것 같습니다.
=> ✨ [Feat] 채용공고 상세 조회 API 구현

src/main/java/com/umc/pyeongsaeng/domain/application/controller/ApplicationController.java, src/main/java/com/umc/pyeongsaeng/domain/application/converter/ApplicationConverter.java, src/main/java/com/umc/pyeongsaeng/domain/application/dto/request/ApplicationRequestDTO.java, src/main/java/com/umc/pyeongsaeng/domain/application/dto/response/ApplicationResponseDTO.java, src/main/java/com/umc/pyeongsaeng/domain/application/entity/ApplicationAnswer.java, src/main/java/com/umc/pyeongsaeng/domain/application/entity/ApplicationAnswerFile.java, src/main/java/com/umc/pyeongsaeng/domain/application/repository/ApplicationAnswerFileRepository.java, src/main/java/com/umc/pyeongsaeng/domain/application/repository/ApplicationAnswerRepository.java, src/main/java/com/umc/pyeongsaeng/domain/application/repository/ApplicationRepositoryImpl.java, src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationCommandService.java, src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationCommandServiceImpl.java, src/main/java/com/umc/pyeongsaeng/domain/job/controller/JobPostController.java, src/main/java/com/umc/pyeongsaeng/domain/job/converter/FormFieldConverter.java, src/main/java/com/umc/pyeongsaeng/domain/job/dto/response/JobPostFormFieldResponseDTO.java, src/main/java/com/umc/pyeongsaeng/domain/job/enums/FieldType.java, src/main/java/com/umc/pyeongsaeng/domain/job/repository/FormFieldRepository.java, src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostQueryService.java, src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostQueryServiceImpl.java, src/main/java/com/umc/pyeongsaeng/global/apiPayload/code/status/ErrorStatus.java
#49 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- get 신청서 작성을 눌렀을 때 그 job_post의 질문(지원동기, 이름 등등), 사용자 맞춤 항목별 선택지를 가져오기
- 신청서 최종 POST API
N/A
- 질문을 가져올 때 AI가 만든 예시 질문들을 같이 만들어서 주면 좋을 듯 합니다.
- AI의 결과에 따라 API가 조금 바뀔 것 같긴 합니다. 일단 생각하고 있는 구조 입니다.
```json
"formFieldList": [
{
"formField": "이름",
"fieldType": "Text"
},
{
"formField": "연락처",
"fieldType": "Text"
},
{
"formField": "지원동기",
"fieldType": "Text"
"fieldAnswerOption" : 
["경제적으로 도움을 얻으려고", "사람들과 만나려고", "사회에 도움이 되려고"]
},
{
"formField": "경력사항",
"fieldType": "IMAGE"
}
]
```
- 동적 폼 때문에 저장이 복잡한데 더 좋은 구조가 있을까 고민이네요
입력 json
```json
{
"jobPostId" : 1,
"seniorId" : 2,
"fieldAndAnswer" : [
{
"formFieldId" …
```
=> ✨ [Feat] 유저 신청서 작성 플로우 

src/main/java/com/umc/pyeongsaeng/domain/application/repository/ApplicationRepository.java, src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationCommandServiceImpl.java, src/main/java/com/umc/pyeongsaeng/domain/application/service/event/ApplicationEventListener.java, src/main/java/com/umc/pyeongsaeng/domain/application/service/event/ApplicationSubmittedEvent.java, src/main/java/com/umc/pyeongsaeng/domain/job/controller/JobPostController.java, src/main/java/com/umc/pyeongsaeng/domain/job/converter/JobPostConverter.java, src/main/java/com/umc/pyeongsaeng/domain/job/search/controller/JobPostSearchController.java, src/main/java/com/umc/pyeongsaeng/domain/job/search/converter/JobPostDocumentConverter.java, src/main/java/com/umc/pyeongsaeng/domain/job/search/document/JobPostDocument.java, src/main/java/com/umc/pyeongsaeng/domain/job/search/dto/request/JobSearchRequest.java, src/main/java/com/umc/pyeongsaeng/domain/job/search/dto/response/JobSearchResponse.java, src/main/java/com/umc/pyeongsaeng/domain/job/search/dto/response/JobSearchResult.java, src/main/java/com/umc/pyeongsaeng/domain/job/search/service/JobPostSearchCommandService.java, src/main/java/com/umc/pyeongsaeng/domain/job/search/service/JobPostSearchCommandServiceImpl.java, src/main/java/com/umc/pyeongsaeng/domain/job/search/service/JobPostSearchQueryService.java, src/main/java/com/umc/pyeongsaeng/domain/job/search/service/JobPostSearchQueryServiceImpl.java, src/main/java/com/umc/pyeongsaeng/domain/senior/controller/SeniorQuestionController.java, src/main/java/com/umc/pyeongsaeng/domain/senior/dto/request/SeniorQuestionRequestDTO.java, src/main/java/com/umc/pyeongsaeng/domain/senior/repository/SeniorQuestionAnswerRepository.java, src/main/java/com/umc/pyeongsaeng/domain/senior/service/SeniorQuestionCommandService.java, src/main/java/com/umc/pyeongsaeng/domain/senior/service/SeniorQuestionCommandServiceImpl.java, src/main/java/com/umc/pyeongsaeng/global/apiPayload/code/status/SuccessStatus.java
closed #52 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
N/A
임금 필드는 현재 검색 조건에 사용되지 않아 검색 대상에서 제외했습니다.  
그리고 마감일(deadline) 기준으로 종료된 공고를 검색 결과에서 제외하도록 했는데, 괜찮을지 의견 부탁드립니다. (OK)
=> ✨ [Feat] 검색 응답 구조 개선 및 시니어 좌표 자동 포함 기능 구현

src/main/java/com/umc/pyeongsaeng/domain/auth/service/OAuth2AuthService.java, src/main/resources/application.yml
#67
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
N/A
=> ♻️ [Refactor] 카카오 로그인 프론트 로컬로 변경

src/main/java/com/umc/pyeongsaeng/domain/application/controller/ApplicationController.java, src/main/java/com/umc/pyeongsaeng/domain/application/dto/request/ApplicationRequestDTO.java, src/main/java/com/umc/pyeongsaeng/domain/application/entity/ApplicationAnswer.java, src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationCommandService.java, src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationCommandServiceImpl.java, src/main/java/com/umc/pyeongsaeng/domain/job/controller/JobPostController.java, src/main/java/com/umc/pyeongsaeng/domain/job/repository/FormFieldRepository.java, src/main/java/com/umc/pyeongsaeng/domain/job/repository/JobPostRepository.java, src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostCommandService.java, src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostCommandServiceImpl.java, src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostQueryService.java, src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostQueryServiceImpl.java
#57 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 회사가 신청서 삭제하는 API Swagger 추가
- 임시 저장 -> 최종 제출로 변경하는 API 생성
- 최종 제출 API 임시저장도 가능하게 수정
- 채용공고 삭제 DELETE API
- 일주일동안 인기가 많은 순으로 조회하는 get API
=> ✨ [Feat] 이번주 지원이 많은 공고 GET, 임시저장한 것을 최종저장으로 PUT 

src/main/java/com/umc/pyeongsaeng/domain/application/controller/ApplicationController.java, src/main/java/com/umc/pyeongsaeng/domain/application/converter/ApplicationConverter.java, src/main/java/com/umc/pyeongsaeng/domain/application/dto/request/ApplicationRequestDTO.java, src/main/java/com/umc/pyeongsaeng/domain/application/dto/response/ApplicationResponseDTO.java, src/main/java/com/umc/pyeongsaeng/domain/application/repository/ApplicationRepository.java, src/main/java/com/umc/pyeongsaeng/domain/application/repository/ApplicationRepositoryCustom.java, src/main/java/com/umc/pyeongsaeng/domain/application/repository/ApplicationRepositoryImpl.java, src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationCommandService.java, src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationCommandServiceImpl.java, src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationQueryService.java, src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationQueryServiceImpl.java, src/main/java/com/umc/pyeongsaeng/domain/job/controller/JobPostController.java, src/main/java/com/umc/pyeongsaeng/domain/job/converter/FormFieldConverter.java, src/main/java/com/umc/pyeongsaeng/domain/job/converter/JobPostConverter.java, src/main/java/com/umc/pyeongsaeng/domain/job/dto/response/FormFieldResponseDTO.java, src/main/java/com/umc/pyeongsaeng/domain/job/entity/JobPost.java, src/main/java/com/umc/pyeongsaeng/domain/job/repository/JobPostRepository.java, src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostCommandServiceImpl.java, src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostQueryService.java, src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostQueryServiceImpl.java
#71 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 사용자가 제출한 신청서 목록조회
- 사용자가 제출한 신청서 상세조회
- 보호자가 대리 신청서를 작성할 때 질문 조회(개인정보에 답이 있다면 추가됨)
- 시니어가 직접 신청서를 작성할 때 질문 조회(개인정보에 답이 있다면 추가됨)
=> ✨ [Feat]  내 정보 플로우에서 신청서 관리 페이지 API

src/main/java/com/umc/pyeongsaeng/domain/application/controller/OpenAiController.java, src/main/java/com/umc/pyeongsaeng/domain/application/dto/request/AnswerGenerationRequestDTO.java, src/main/java/com/umc/pyeongsaeng/domain/application/service/OpenAiService.java, src/main/java/com/umc/pyeongsaeng/domain/application/service/OpenAiServiceImpl.java, src/main/java/com/umc/pyeongsaeng/domain/application/util/OpenAiPromptBuilder.java
closed #75  : AI 기반 지원서 자동작성 기능 구현
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 기존 답변에 ‘추가 경험’을 반영하여 보강 답변을 생성하는 API (`/api/ai/updated-answers`) 추가
- Controller에 Swagger 문서화 적용 
=> ✨[Feat]  OpenAI 추가 정보 기반 답변 업데이트 기능 구현

src/main/java/com/umc/pyeongsaeng/domain/application/controller/ApplicationController.java, src/main/java/com/umc/pyeongsaeng/domain/application/entity/Application.java, src/main/java/com/umc/pyeongsaeng/domain/application/repository/ApplicationRepository.java, src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationCommandService.java, src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationCommandServiceImpl.java, src/main/java/com/umc/pyeongsaeng/domain/bookmark/controller/BookmarkController.java, src/main/java/com/umc/pyeongsaeng/domain/bookmark/dto/response/BookmarkResponseDTO.java, src/main/java/com/umc/pyeongsaeng/domain/bookmark/entity/Bookmark.java, src/main/java/com/umc/pyeongsaeng/domain/bookmark/repository/BookmarkRepository.java, src/main/java/com/umc/pyeongsaeng/domain/bookmark/service/BookmarkCommandServiceImpl.java, src/main/java/com/umc/pyeongsaeng/domain/bookmark/service/BookmarkQueryServiceImpl.java, src/main/java/com/umc/pyeongsaeng/domain/job/search/controller/JobPostSearchController.java, src/main/java/com/umc/pyeongsaeng/global/apiPayload/code/status/SuccessStatus.java, src/main/java/com/umc/pyeongsaeng/global/common/BaseEntity.java
closed #78 
어떤 변경사항이 있었나요?
N/A
일자리 저장함(북마크)과 신청함에서 삭제 시 발생할 수 있는 오류를 방지하기 위해 관련 로직을 추가했습니당.
=> ✨ [Feat] 일자리 저장함 동일 북마크 저장 방지 로직 추가, 신청 클릭 시 updatedAt 갱신

src/main/java/com/umc/pyeongsaeng/domain/application/converter/ApplicationConverter.java, src/main/java/com/umc/pyeongsaeng/domain/application/dto/response/ApplicationResponseDTO.java, src/main/java/com/umc/pyeongsaeng/domain/application/repository/ApplicationRepositoryImpl.java
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- application/me/submitted에서 applicationStatus를 보내도록 수정
- 하면서 쿼리문에 NON_STARTED제외하는거 추가 
N/A
=> ✨ [Feat] application/me/submitted에서 applicationStatus를 보내도록 수정

src/main/java/com/umc/pyeongsaeng/domain/application/dto/request/ApplicationRequestDTO.java
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- NotBlank채용공고 등록에 잘못 적용한거 수정
N/a
=> 🐛 [Fix] NotBlank채용공고 등록에 잘못 적용한거 수정

src/main/java/com/umc/pyeongsaeng/domain/application/controller/ApplicationController.java, src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationQueryService.java, src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationQueryServiceImpl.java
#87 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 보호자가 시니어가 제출한 게시글 목록 조회
N/A
=> ✨ [Feat] 보호자가 시니어가 제출한 게시글 목록 조회

src/main/java/com/umc/pyeongsaeng/domain/application/controller/ApplicationController.java, src/main/java/com/umc/pyeongsaeng/domain/application/converter/ApplicationConverter.java, src/main/java/com/umc/pyeongsaeng/domain/application/dto/response/ApplicationResponseDTO.java
#92 
어떤 변경사항이 있었나요?
- [] 🔨 Refactor Code refactoring
작업 내용을 작성해주세요.
- 보호자가 시니어가 작성한 제출된 지원서 하나를 상세조회
N/A
=> ✨ [Feat] 보호자가 시니어가 작성한 제출된 지원서 하나를 상세조회
